_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
                - 55
            "4": 3.12.9
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 8
beta_end:
    value: "0.02"
beta_schedule:
    value: linear
beta_start:
    value: "0.0001"
cfg_guidance_scale:
    value: 2
ckpt:
    value: null
clip_sample:
    value: true
clip_sample_range:
    value: 1
config:
    value: configs/ddpm.yaml
data_dir:
    value: ../data/subset
device:
    value: cuda
distributed:
    value: false
grad_clip:
    value: 1
image_size:
    value: 32
is_cifar_10:
    value: false
latent_ddpm:
    value: false
learning_rate:
    value: "0.0005"
local_rank:
    value: 0
max_train_steps:
    value: 700
mixed_precision:
    value: none
num_classes:
    value: 10
num_epochs:
    value: 100
num_inference_steps:
    value: 1000
num_train_timesteps:
    value: 1000
num_workers:
    value: 2
optimizer_type:
    value: AdamW
output_dir:
    value: /ocean/projects/cis250019p/jye9/11685-project/experiments
prediction_type:
    value: epsilon
predictor_type:
    value: epsilon
pretrained_vae:
    value: /ocean/projects/cis250019p/jye9/11685-project/pretrained/model.ckpt
rank:
    value: 0
run_name:
    value: exp-3-ddpm
scheduler_type:
    value: ConsineAnnealingLR
seed:
    value: 42
total_batch_size:
    value: 8
unet_attn:
    value: []
unet_ch:
    value: 64
unet_ch_mult:
    value:
        - 1
        - 2
        - 2
        - 2
unet_dropout:
    value: "0.0"
unet_in_ch:
    value: 3
unet_in_size:
    value: 32
unet_num_res_blocks:
    value: 2
use_cfg:
    value: false
use_ddim:
    value: false
use_val:
    value: false
variance_type:
    value: fixed_small
weight_decay:
    value: 0
world_size:
    value: 1
