#!/bin/bash
#SBATCH --job-name=inference       # Job name
#SBATCH --output=log/inference.log      # Output file (%j = job ID)
#SBATCH --time=02:00:00             # Walltime (hh:mm:ss)
#SBATCH --nodes=1                   # Number of nodes
#SBATCH --partition=GPU-shared         # Partition/queue name
#SBATCH --gpus=v100-32:1
#SBATCH -A cis250227p


module load anaconda3
conda activate /ocean/projects/cis250019p/jye9/conda/envs/11685

python inference.py --config configs/ddim.yaml
