run_name: ddpm
seed: 42
# data_dir: ../data
data_dir: /ocean/projects/cis250019p/jye9/11685-project/data
image_size: 32
batch_size: 32
num_workers: 4
num_classes: 10
num_epochs: 300
learning_rate: 5e-4
weight_decay: 0
num_train_timesteps: 500
num_inference_steps: 500
beta_start: 0.0001
beta_end: 0.1  
beta_schedule: cosine

variance_type: fixed_small
predictor_type: epsilon
unet_in_size: 32
unet_in_ch: 3
unet_ch: 64
unet_num_res_blocks: 1
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2,3] #[1, 2, 3]
unet_dropout: 0.2
use_ddim: False
use_cfg: False
latent_ddpm: False
output_dir: /ocean/projects/cis250019p/jye9/11685-project/experiments
pretrained_vae: /ocean/projects/cis250019p/jye9/11685-project/pretrained/model.ckpt

use_val: True
is_cifar_10: True